version: "3"

services:
 app:
  build:
   context: .
   dockerfile: dockerfile
  image: phpservice
  container_name: app
  restart: unless-stopped
  volumes:
   - ./www/:/var/www
 webserver:
  build:
   context: .
   dockerfile: dockerfile_nginx
  image: nginx
  container_name: webserver
  restart: unless-stopped
  ports:
   - "8080:80"
  volumes:
   - ./www/:/var/www
   - ./nginx/:/etc/nginx/conf.d/
  depends_on:
   - app
 db:
  image: mysql:5.7.22
  container_name: db
  environment:
   MYSQL_DATABASE: basedados
   MYSQL_ROOT_PASSWORD: admin
  ports:
   - "3307:3306"
  volumes:
   - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/1.sql
   - ./scripts/dml.sql:/docker-entrypoint-initdb.d/2.sql

   